chore: merge v23
linuxdeepin/deepin-wallpapers pull request #25
Opened 2023-02-03 05:29 UTC by Zeno-sole

2023-02-03 05:31 UTC, Zeno-sole commented
I have read the CLA Document and I hereby sign the CLA.

2023-02-03 05:32 UTC, Zeno-sole commented
/check clacheck

2023-02-03 05:34 UTC, Zeno-sole commented
/check

2023-02-03 05:36 UTC, Zeno-sole commented
@BLumia  包含历史提交，以前的开发者没有签署cla

2023-02-03 05:46 UTC, BLumia requested changes
这个和 https://github.com/linuxdeepin/deepin-wallpapers/pull/24 存在一样的问题，好像把非自由的壁纸（来自 unsplash 的）放到了这个仓库。按照之前 @justforlxz 讨论的结果，非自由的应该在 deepin-wallpapers-nonfree 吧？

> 以前的开发者没有签署cla

CLA 可以忽略掉

2023-02-03 06:41 UTC, Zeno-sole commented
> 这个和 #24 存在一样的问题，好像把非自由的壁纸（来自 unsplash 的）放到了这个仓库。按照之前 @justforlxz 讨论的结果，非自由的应该在 deepin-wallpapers-nonfree 吧？
> 
> > 以前的开发者没有签署cla
> 
> CLA 可以忽略掉，这个不要紧。另外 REUSE 检查也可以暂时放到后面修，但非自由壁纸的问题最好先解决再合并，不然合并会产生自动 tag 导致 tag 版本是存在问题的了。

这个应该是处理过的，nonfree里面的壁纸在这里并没有重复包含

2023-02-03 06:42 UTC, Zeno-sole commented
@justforlxz   瞅一眼？

2023-02-03 08:31 UTC, Zeno-sole commented
> @justforlxz 瞅一眼？

@justforlxz  已经移除了

2023-02-06 07:26 UTC, justforlxz approved these changes

2023-02-06 07:26 UTC, BLumia approved these changes
经 @justforlxz 确认已调整完毕

2023-02-06 07:33 UTC, merged